# Generated by Django 3.2 on 2022-09-05 11:23

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('label', models.CharField(blank=True, max_length=80, null=True)),
                ('class_name', models.CharField(max_length=80)),
                ('template_areas', models.TextField(blank=True, help_text='Encapsulate rows with quotes', null=True)),
                ('grid_template_columns', models.CharField(blank=True, help_text='1fr 10px 1fr', max_length=255, null=True)),
                ('grid_template_rows', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsgrid_grid', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GridItem',
            fields=[
                ('label', models.CharField(blank=True, max_length=80, null=True)),
                ('gridarea', models.CharField(blank=True, max_length=80, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsgrid_griditem', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
